Revert "Merge pull request #385 from takakuda/feature/conditions_change"
This reverts commit 00e14aa186917b557a6ccb2c08ea89e56f3faad1, reversing
changes made to f796d366444d454e12a65cf1db81781dc0ce2c7b.

Reason: The pure Ruby doesn't have `Array#present?`. So this cause
`NoMethodError` when using dotenv without Rails.

```
$ dotenv -t .env
Traceback (most recent call last):
	3: from /bin/dotenv:23:in `<main>'
	2: from /bin/dotenv:23:in `load'
	1: from /lib/ruby/gems/2.5.0/gems/dotenv-2.7.3/bin/dotenv:4:in `<top (required)>'
/lib/ruby/gems/2.5.0/gems/dotenv-2.7.3/lib/dotenv/cli.rb:25:in `run': undefined method `present?' for []:Array (NoMethodError)
Did you mean?  prepend
```