Add save_env
Safe env is a 3 line snippet conceived by Oliver Searle-Barnes
(https://github.com/opsb):

  SAFE_ENV = Proc.new do |name|
    ENV[name].tap{ |value| raise "Environment variable #{name} is missing" unless value }
  end

`SAFE_ENV` works like `ENV` except it will raise an error if the
environment variable does not exists:

  [1] pry(main)> SAFE_ENV['CITY_OF_ATLANTIS']
  RuntimeError: Environment variable CITY_OF_ATLANTIS is missing